name: CI/CD with Github Actions

on:
  push:
    branches:
      - "main"
      - "master"
      - "ft/aws-ecr"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Assumindo que você usará tags no formato semver, como v1.0.0
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/payment-service"
          IMAGE_TAG="${GITHUB_SHA}"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$TAG
          fi

      - name: Push Image to Docker Hub
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/payment-service"
          IMAGE_TAG="${GITHUB_SHA}"
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker push $IMAGE_NAME:$TAG
          fi

      - name: Tag and Push Docker Image to AWS ECR
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/payment-service"
          IMAGE_TAG="${GITHUB_SHA}"

          docker tag $IMAGE_NAME:latest ${{ secrets.IMAGE_REPOSITORY_URL }}:latest
          docker push ${{ secrets.IMAGE_REPOSITORY_URL }}:latest

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.IMAGE_REPOSITORY_URL }}:$TAG
            docker push ${{ secrets.IMAGE_REPOSITORY_URL }}:$TAG
          fi