name: CI/CD with Github Actions

on:
  push:
    branches:
      - "main"
      - "master"
      - "ft/aws-ecr"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        working-directory: ./
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }} .
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker tag ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/payment-service:$TAG
          fi

      - name: Push Image to Docker Hub Container Registry
        working-directory: ./
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:$TAG
          fi

      - name: Tag and Push Docker Image to AWS ECR
        working-directory: ./
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/payment-service:latest ${{ secrets.IMAGE_REPOSITORY_URL }}:latest

          docker push ${{ secrets.IMAGE_REPOSITORY_URL }}:latest

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker push ${{ secrets.IMAGE_REPOSITORY_URL }}:$TAG
          fi