name: CI/CD with Github Actions

on:
  push:
    branches:
      - "main"
      - "master"
    tags:
      - '[0-9]+.[0-9]+.[0-9]'
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Application .jar
        working-directory: ./
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Build Docker Image
        working-directory: ./
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }} .
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker tag ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/payment-service:$TAG
          fi

      - name: Push Image to Docker Hub Container Registry
        working-directory: ./
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:$TAG
          fi