name: CI/CD with Github Actions

on:
  push:
    branches:
      - "main"
      - "ft/github-actions"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Application .jar
        working-directory: ./
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Build Docker Image
        working-directory: ./
        run: docker build -t moraessit/payment-service:0.0.1-SNAPSHOT .

      - name: Push Image to Docker Hub Container Registry
        working-directory: ./
        run: docker push moraessit/payment-service:0.0.1-SNAPSHOT
